title: Bootstrap-debugger
description: A small piece of code to debug bootstrap responsive layouts.
google_analytics: UA-8309890-14
show_downloads: true
theme: jekyll-theme-architect

gems:
  - jekyll-mentions
